In [6]:
from keras import backend as K
from keras.layers import Layer
import numpy as np

Using Theano backend.
Using gpu device 0: Tesla K40c (CNMeM is disabled, cuDNN 5103)


In [7]:
def power_mean_betas(input,p,along_axis):
    #return T.max(x,axis=1) * (1.0**p)
    temp=K.reshape(input* p[None,:,None,None], (input.shape[0]*input.shape[1], input.shape[2]*input.shape[3]))
    x=K.reshape(input, (input.shape[0]*input.shape[1], input.shape[2]*input.shape[3]))
    output = K.sum(K.theano.tensor.
                   nnet.softmax(temp) * x , axis=along_axis)
    return K.reshape(output,(input.shape[0], input.shape[1],1))

def power_mean_beta(input,p,along_axis):
    #return T.max(x,axis=1) * (1.0**p)
    x=K.reshape(input, (input.shape[0]*input.shape[1], input.shape[2]*input.shape[3]))
    output = K.sum(K.theano.tensor.nnet.softmax(x * p) * x , axis=along_axis)
    return K.reshape(output,(input.shape[0], input.shape[1],1))

In [8]:
class power_mean_Layer(Layer):
    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)
    def call(self, x,p, mask=None):    
        return power_mean_betas(x,p,along_axis)
    def get_output_shape_for(self, input_shape):
        return (input_shape[0], input_shape[1],1)

In [9]:
p=K.theano.tensor.vector()
p_scalar=K.theano.tensor.scalar()
input=K.theano.tensor.tensor4()
#power_mean(input,p,1)
f=K.theano.function([input,p],[power_mean_betas(input,p,1)])
f2=K.theano.function([input,p_scalar],[power_mean_beta(input,p_scalar,1)])

In [1]:
import numpy as np
B = np.random.random((2,2,2,2))
B=B.astype(np.float32)
B

array([[[[ 0.44649726,  0.32659942],
         [ 0.50427538,  0.56817687]],

        [[ 0.00234388,  0.32934645],
         [ 0.43834636,  0.74206126]]],


       [[[ 0.41586864,  0.30069202],
         [ 0.99336916,  0.40483528]],

        [[ 0.35489613,  0.43427119],
         [ 0.84226733,  0.00313834]]]], dtype=float32)

In [11]:
betas=np.array([0.0,1.0])
betas=betas.astype(np.float32)
print f(B,betas)

beta=np.float32(0.0)
#print f2(B,beta)[0]

print f(B,betas)[0]

[array([[[ 0.46138722],
        [ 0.44651115]],

       [[ 0.52869129],
        [ 0.49806112]]], dtype=float32)]
[[[ 0.46138722]
  [ 0.44651115]]

 [[ 0.52869129]
  [ 0.49806112]]]


In [30]:
f

In [36]:
numpy.float32

numpy.float32

In [44]:
betas[:,None]

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32)

In [59]:
betas=np.array([0.0,5.0])
B*betas[np.newaxis,:,np.newaxis,np.newaxis]

array([[[[ 0.        ,  0.        ],
         [ 0.        ,  0.        ]],

        [[ 0.10760076,  4.82928544],
         [ 0.11758095,  1.75946206]]],


       [[[ 0.        ,  0.        ],
         [ 0.        ,  0.        ]],

        [[ 0.85238189,  0.82604259],
         [ 4.87081677,  1.6329594 ]]]])

In [81]:
import random
def random_float(low, high,N):
    arr=[]
    for i in range(N):
        arr.append(random.random()*(high-low) + low)
    return np.array(arr)

In [85]:
random_float(0, 1,10)

array([ 0.9217244 ,  0.46935402,  0.1840877 ,  0.95879546,  0.10404153,
        0.94298431,  0.42553939,  0.42270785,  0.45661278,  0.01026737])